# Generated by Django 3.1.1 on 2020-10-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('records', '0002_auto_20200922_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='medical_book',
        ),
        migrations.AddField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MedicalBook',
        ),
    ]
