# Generated by Django 3.1.1 on 2020-09-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='spec',
            field=models.ManyToManyField(blank=True, to='hospital_auth.Specialization'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='patients', to='hospital_auth.Doctor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
