# Generated by Django 3.1.1 on 2020-09-11 06:40

from django.db import migrations, models
import hospital_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0003_auto_20200908_0942'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', hospital_auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
